services:
  airflow-db:
    image: ghcr.io/gigaflux/airflow-db:17
    container_name: airflow-db
    hostname: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD_FILE=/usr/local/etc/postgres/postgres.pwd
      - POSTGRES_DB=airflow
      - POSTGRES_INIT=/usr/local/bin/pg_init
    volumes:
      - airflow-db_data:/var/lib/postgresql/data
      - ./airflow.conf:/etc/postgresql/conf.d/airflow.conf:ro
      - ./init:/usr/local/bin/pg_init:ro
      - ../../../var/.vault/users/postgres:/tmp/postgres:ro
    entrypoint: [ ]
    command: >
      bash -c '
        set -e
        set -o pipefail
        mkdir -p /usr/local/etc/postgres
        cp -r /tmp/postgres/. /usr/local/etc/postgres/
        chmod 400 /usr/local/etc/postgres/postgres.key
        chmod 400 /usr/local/etc/postgres/postgres.pwd
        chown -R postgres:postgres /usr/local/etc/postgres
        exec bash /usr/local/bin/pg_init/init.sh
      '
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-net

volumes:
  airflow-db_data:
    name: airflow-db_data
    external: true

networks:
  airflow-net:
    external: true
