services:
  airflow-db:
    image: ghcr.io/gigaflux/airflow-db:17
    container_name: airflow-db
    hostname: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD_FILE=/usr/local/etc/postgres/postgres.pwd
      - POSTGRES_DB=airflow
      - POSTGRES_INIT=/usr/local/bin/pg_init
    volumes:
      - airflow-db_data:/var/lib/postgresql/data
      - ./airflow.conf:/etc/postgresql/conf.d/airflow.conf:ro
      - ./init:/usr/local/bin/pg_init:ro
      - ../../../var/.vault:/tmp/.vault:ro
    entrypoint: [ ]
    command: >
      sh -c 'mkdir -p /usr/local/etc/postgres &&
            cp -r /tmp/.vault/airflow-db/. /usr/local/etc/postgres/ &&
            cp -f /tmp/.vault/ca/ca.crt /usr/local/etc/postgres/ &&
            chown postgres:postgres -R /usr/local/etc/postgres &&
            /bin/bash /usr/local/bin/pg_init/init.sh'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-net

volumes:
  airflow-db_data:
    name: airflow-db_data
    external: true

networks:
  airflow-net:
    external: true
